# -*- coding: utf-8 -*-
"""Copy of hermite.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1POOIPYK_Yw-mFjdAreTxwI3uwAA3oS_k
"""

import numpy as np
import scipy as sp
import sympy as smp
import matplotlib.pyplot as plt
import scipy.misc
import derivative



x,a,b = smp.symbols('x a b' , real=True)
f = smp.exp(-a*x**2)*smp.exp(smp.exp(b*x**2-1))
d3fdx3 = smp.diff(f,x,3)
d3fdx3

!pip install derivative